### PR TITLE
Fix example app tooling issues

### LINKED ISSUE #14: Update eslint config so example app is properly linted

### PR DESCRIPTION
**Pull request by zakangelle**
This PR addresses some follow-ups after adding the `example` app.

Important things:

+ Add `react` and `react-dom` dependencies to `example` project, since they are now expressed as peer dependencies in `use-fetch-hooks`
+ Enable prettier to prettify `example`
+ Fix prettier bug where fixes weren't being committed with staged changes (see [option 2 here](https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick) for more details on this configuration)
+ Resolve linting errors

Closes #14

### CODE REVIEW

File: example/src/useLazyFetch/Basic.jsx [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import React from 'react';
-import { useLazyFetch } from 'use-fetch-hooks';
+import { useLazyFetch } from '../../../src';
```
Comment (zakangelle) [inline example/src/useLazyFetch/Basic.jsx]: This is uglier but it's easier than having to alias `use-fetch-hooks` in both `webpack` and `eslint` config (as well as other tooling).

File: example/webpack.config.js [hunk 2]
```diff
@@ -22,7 +22,8 @@ module.exports = {
   resolve: {
     extensions: ['.js', '.jsx'],
     alias: {
-      'use-fetch-hooks': path.resolve(__dirname, '../src'),
+      react: path.resolve(__dirname, './node_modules/react'),
+      'react-dom': path.resolve(__dirname, './node_modules/react-dom'),
```
Comment (zakangelle) [inline example/webpack.config.js]: This ensures that `react` and `react-dom` imports in `use-fetch-hooks` resolve to the `node_modules` in `example`. This is necessary since `use-fetch-hooks` does not install its own versions of these libraries anymore.

File: package.json [hunk 3]
```diff
@@ -43,17 +43,18 @@
...
-      "pre-commit": "npm run prettier"
-    }
-  },
   "peerDependencies": {
     "react": ">=16.8.0",
     "react-dom": ">=16.8.0"
+  },
+  "husky": {
+    "hooks": {
+      "pre-commit": "pretty-quick --staged"
```
Comment (jpangelle) [inline package.json]: nice
